[package]
name = "galleonfs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "galleonfs"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"
crc32fast = "1.3"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
base64 = "0.21"
serde_json = "1.0"
notify = "6.0"
# FUSE support (Linux/macOS only)
[target.'cfg(unix)'.dependencies]
fuser = { version = "0.14", optional = true }
libc = { version = "0.2", optional = true }

[features]
default = ["fuse"]
fuse = ["fuser", "libc"]

[dev-dependencies]
tempfile = "3.0"